services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=exam
      - MARIADB_PASSWORD=exam
      - MARIADB_DATABASE=exam
      - MARIADB_ROOT_PASSWORD=exam
    volumes:
      - 'db-data:/bitnami/mariadb'
  quiz:
    build:
      context: .
    ports:
      - '80:80'
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=exam
      - DB_NAME=exam
      - DB_PASSWORD=exam
      - DOMAINNAME=ec2-54-70-46-141.us-west-2.compute.amazonaws.com
    depends_on:
      - mariadb

volumes:
  db-data:
