services:
  mariadb:
    image: nourddinelearning/mariadb-gam_quiz:v2025.09.16
    container_name: mariadb_gam_quiz
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=exam
      - MARIADB_PASSWORD=exam
      - MARIADB_DATABASE=exam
      - MARIADB_ROOT_PASSWORD=exam
    volumes:
      - './data/mariadb:/bitnami/mariadb'
  quiz:
    image: nourddinelearning/gam_quiz:v2025.09.16
    container_name: quiz_gam_quiz
    ports:
      - '80:80'
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=exam
      - DB_NAME=exam
      - DB_PASSWORD=exam
      - DOMAINNAME=nour.eastus.cloudapp.azure.com
    depends_on:
      - mariadb

volumes:
  db-data:
