name: Docker Publish

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  # Set in repo secrets: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN

jobs:
  build-and-push-app:
    name: Build and Push App Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute date tag
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Docker meta (app)
        id: meta_app
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/savsoftquiz-gam_quiz
          tags: |
            type=raw,value=latest
            type=raw,value=v${{ steps.date.outputs.date }}
            type=sha,prefix=sha-,format=short
            type=ref,event=tag

      - name: Build and push (app)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta_app.outputs.tags }}
          labels: ${{ steps.meta_app.outputs.labels }}

  retag-and-push-db:
    name: Retag and Push DB Image
    runs-on: ubuntu-latest
    needs: build-and-push-app
    permissions:
      contents: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull upstream MariaDB image (10.6)
        run: docker pull docker.io/bitnami/mariadb:10.6

      - name: Retag for user namespace
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          set -euo pipefail
          docker tag docker.io/bitnami/mariadb:10.6 ${USER}/mariadb-gam_quiz:10.6
          docker tag docker.io/bitnami/mariadb:10.6 ${USER}/mariadb-gam_quiz:latest

      - name: Push DB image tags
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push ${USER}/mariadb-gam_quiz:10.6
          docker push ${USER}/mariadb-gam_quiz:latest

